### ISSUE TITLE
QVEG - request for documentation

### ISSUE THREAD

**Issue by JU20** [PattemoreSoftware/Qveg#1]
Hi there, 
I installed QVEG but I don't know how to get it to work.  Could you please provide some insights?  Do I need to manually connect to something?  
Thanks,

**Comment by GaryPattemore** [comment]
Hi @JU20 ,
Thank you for your question. Sorry for the lack of documentation - it's something that I'm hoping to address in the near future.
The tools provided by Qveg are available in the Processing Toolbox. This can be opened from the main menu bar under Processing > Toolbox. In the image below you can see the Processing Toolbox on the right and the menu selection highlighted in blue in the main menu bar.
![Screenshot from 2023-01-09 15-54-52](https://user-images.githubusercontent.com/57279255/211248765-5014c16a-4de9-49b4-94ca-a29eaeb4f223.png)

And then to get you started,
![image](https://user-images.githubusercontent.com/57279255/211249867-fe6cd6ba-88e0-4482-9068-061e72c7131a.png)


And...
![image](https://user-images.githubusercontent.com/57279255/211249628-604c3d48-f2af-4b8d-a9bc-87d6f246f01b.png)

Please let me know if you require further assistance - happy to help! :smile: 

Kind regards,
Gary.

**Comment by GaryPattemore** [comment]
Closing as resolved.
